language: node_js
node_js: 
  - lts/*

script:
  - npm install
  - npm run export
 
deploy:
  local_dir: __sapper__/export
  fqdn: ssb.aboni.dev
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
  branch: master
